site_name: miguelarbesu/pulsecalc
repo_name: miguelarbesu/pulsecalc
repo_url: https://github.com/miguelarbesu/pulsecalc
theme:
  name: material
  palette:
    primary: blue grey
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - navigation.tabs.sticky
plugins:
  - search
  - mkdocstrings:
      watch:
        - src/pulsecalc
